# Generated by Django 4.2 on 2023-04-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default='2023-01-01 00:00:00', verbose_name='Время записи')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер задания')),
                ('qr', models.CharField(blank=True, max_length=30, null=True, verbose_name='QR-код поставки')),
                ('sticker', models.CharField(blank=True, max_length=20, null=True, verbose_name='Стикер ')),
                ('created_at_order', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('name_product', models.TextField(blank=True, null=True, verbose_name='Название товара')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость')),
                ('code_wid', models.IntegerField(blank=True, null=True, verbose_name='Артикул Wildberries')),
                ('code_prod', models.CharField(db_index=True, max_length=100, verbose_name='Артикул продавца')),
                ('status', models.CharField(max_length=50, verbose_name='Статус задания')),
                ('duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время с момента заказа')),
                ('path_files', models.TextField(blank=True, null=True, verbose_name='Папка с файлами заказа')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='Размер значка')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество значков в наборе')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('code_prod', '-created_at'),
                'index_together': {('code_prod',)},
            },
        ),
    ]
